HR/urls.py
from django.urls import path
from . import views
urlpatterns = (
    path('', views.Index),
    path('ajax/wgps/', views.ajax_wgps, name='ajax_wgps'),
    

)

djangovue/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mi/', include('mi_website.urls')),
    path('ppc/', include('ppc.urls')),
    #path('design/', include('design.urls')),
    path('hr/', include('HR.urls')),
    path('mtpinfoshare/', include('mtpinfoshare.urls')),
     path('purchase/', include('purchase.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mi_website/urls.py
from django.conf.urls import url,include
from django.urls import path,re_path
from . import views

urlpatterns = (
    #url(r'^(?i)login/$', views.showLoginPage, name='login'),
    path('test', views.test),
    path('', views.Index),
    path('mainstore/', views.mainstorehome, name='mainstore'),
    path('mislipview/', views.mislipview, name='mislipview'),

    path('mislips/', views.ajax_mislips, name='ajax_mislips'),
    path('ajax/mislipedit/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mislipdate>', views.mislipedit, name='mislipedit'),
    path('ajax/mislipdel/<str:finyear>/<int:mislipno>/<int:matgrp>', views.mislipdel, name='mislipdel'),
    path('ajax/mislipprint/<str:finyear>/<int:mislipno>/<int:matgrp>', views.mislipprint, name='mislipprint'),

    path('ajax/mislipcreate/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mislipdate>', views.mislipcreate, name='mislipcreate'),
    path('ajax/getsuppaddfrompono/', views.getsuppaddfrompono, name='getsuppaddfrompono'),

    path('mislipitems/', views.ajax_mislipitems, name='mislipitems'),
    path('ajax/mislipitemedit/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:stockno>', views.mislipitemedit, name='mislipitemedit'),
    path('ajax/mislipitemdel/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:stockno>', views.mislipitemdel, name='mislipitemdel'),

    path('ajax/mislipitemcreate/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:stockno>', views.mislipitemcreate, name='mislipitemcreate'),
    path('ajax/getstocknodes/', views.getdesfromstockno, name='getstocknodes'),

    path('mislipmrrs/', views.ajax_mislipmrrs, name='mislipmrrs'),
    path('ajax/mislipmrredit/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mrrno>', views.mislipmrredit,
         name='mislipmrredit'),
    path('ajax/mislipmrrdel/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mrrno>', views.mislipmrrdel,
         name='mislipmrrdel'),

    path('ajax/mislipmrrcreate/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mrrno>', views.mislipmrrcreate,
         name='mislipmrrcreate'),

    path('mislipbills/', views.ajax_mislipbills, name='mislipbills'),
    path('ajax/mislipbilledit/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:billno>/<str:billtype>', views.mislipbilledit,
         name='mislipbilledit'),
    path('ajax/mislipbilldel/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:billno>/<str:billtype>', views.mislipbilldel,
         name='mislipbilldel'),

    path('ajax/mislipbillcreate/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:billno>/<str:billtype>', views.mislipbillcreate,
         name='mislipbillcreate'),

    path('mrrview/', views.mrrview, name='mrrview'),
    path('mrrs/', views.ajax_mrrs, name='ajax_mrrs'),
    path('ajax/mrredit/<str:finyear>/<int:mrrno>/<str:mrrdate>', views.mrredit, name='mrredit'),
    path('ajax/mrrdel/<str:finyear>/<int:mrrno>/', views.mrrdel, name='mrrdel'),
    path('ajax/mrrcreate/<str:finyear>/<int:mrrno>/<str:mrrdate>', views.mrrcreate, name='mrrcreate'),

    path('mrrvalues/', views.ajax_mrrvalues, name='mrrvalues'),
    path('ajax/mrrvalueedit/<str:finyear>/<int:mrrno>/<str:billno>', views.mrrvalueedit, name='mrrvalueedit'),
    path('ajax/mrrvaluedel/<str:finyear>/<int:mrrno>/<str:billno>', views.mrrvaluedel, name='mrrvaluedel'),
    path('ajax/mrrvaluecreate/<str:finyear>/<int:mrrno>/<str:billno>', views.mrrvaluecreate, name='mrrvaluecreate'),

    path('ledgerview/', views.ledgerview, name='ledgerview'),
    path('ledger/', views.ajax_ledger, name='ajax_ledger'),
    path('ajax/ledgeredit/<str:finyear>/<str:stockno>/<int:matgroup>/<str:transid>', views.ledgeredit, name='ledgeredit'),
    path('ajax/ledgerdel/<str:transid>/', views.ledgerdel, name='ledgerdel'),
    path('ajax/ledgercreate/<str:finyear>/<str:stockno>/<int:matgroup>/<str:transid>/', views.ledgercreate, name='ledgercreate'),

    path('ajax/updatewon/', views.updateWON,name='updatewon'),

    path('stmislipsview/', views.stmislipsview, name='stmislipsview'),

    path('stdocregisterview/', views.stdocregisterview, name='stdocregisterview'),
    path('ajax/stdocregister/', views.ajax_stdocregister, name='ajax_stdocregister'),
    path('ajax/stdocregisteredit/<str:yearid>/<int:groupid>/<int:docno>/<int:doctype>', views.stdocregisteredit, name='stdocregisteredit'),
    path('ajax/stdocregisterdel/<str:yearid>/<int:groupid>/<int:docno>/<int:doctype>', views.stdocregisterdel, name='stdocregisterdel'),
    path('ajax/stdocregistercreate/<str:yearid>/<int:groupid>/<int:docno>/<int:doctype>', views.stdocregistercreate, name='stdocregistercreate'),
    path('ajax/stdocledger/', views.ajax_stdocledger, name='ajax_stdocledger'),

    path('stmislipsview/', views.stmislipsview, name='stmislipsview'),
    path('ajax/stmislips/', views.ajax_stmislips, name='ajax_stmislips'),
    path('ajax/stmislipedit/<str:finyear>/<int:mislipno>/<int:matgrp>/<str:mislipdate>', views.stmislipedit,
         name='stmislipedit'),

    path('ajax/stmislipitems/', views.ajax_stmislipitems, name='ajax_stmislipitems'),
    path('ajax/stmislipitemsedit/<str:yearid>/<int:docref>/<str:stockno>', views.stmislipitemsedit, name='stmislipitemsedit'),
    path('ajax/stmislipitemsdel/<str:yearid>/<int:groupid>/<int:docno>/<int:doctype>', views.stmislipitemsdel, name='stmislipitemsdel'),
    path('ajax/stmislipitemscreate/<str:yearid>/<int:groupid>/<int:docno>/<int:doctype>', views.stmislipitemscreate, name='stmislipitemscreate'),

    path('ststockmasterview/', views.ststockmasterview, name='ststockmasterview'),
    path('ajax/ststockmaster/', views.ajax_ststockmaster, name='ajax_ststockmaster'),
    path('ajax/ststockmasteredit/<str:stockno>', views.ststockmasteredit, name='ststockmasteredit'),
    path('ajax/ststockmasterdel/<str:stockno>', views.ststockmasterdel, name='ststockmasterdel'),
    path('ajax/ststockmastercreate/<str:stockno>', views.ststockmastercreate, name='ststockmastercreate'),

    path('ajax/getcurrentyear', views.getcurrentyear, name='getcurrentyear'),
    path('ajax/getmatgroups', views.getmatgroups, name='getmatgroups'),




)

mi_website/models.py
from django.db import models

mi_website/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import  Submit,Layout,Div,Button,Fieldset,Field
import datetime
from django.forms import widgets

from mi_website.formvalidators_choices import *

class bformdatepicker(widgets.TextInput):
    template_name='mi_website/widgets/b-form-datepicker.html'

class mislipeditForm(forms.Form):
    


    finyear = forms.CharField(max_length=50)
    finyear.widget.attrs['readonly'] = True
    mislipdate = forms.DateField(input_formats=["%d-%b-%Y"])
    mislipdate.widget.attrs['readonly'] = True
    matgrp=forms.IntegerField()
    matgrp.widget.attrs['readonly'] = True
    mislipno=forms.IntegerField()
    mislipno.widget.attrs['readonly'] = True
    pono=forms.IntegerField()
    suppname=forms.CharField(widget=forms.Textarea(attrs={'rows':5}),max_length=200)
    mprno = forms.CharField(max_length=50)
    recdby = forms.CharField(max_length=50)
    note = forms.CharField(max_length=50,required=False)
    st_auth = forms.BooleanField(required=False)
    mst_auth= forms.BooleanField(required=False)
    mst_auth_date=forms.DateField(widget=bformdatepicker(),required=False)
    #username = forms.CharField(widget=forms.HiddenInput(), required=True)

    def __init__(self, *args, **kwargs):
        super(mislipeditForm,self).__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.render_hidden_fields = True
        self.helper.layout = Layout(
            Div(
                Div('st_auth', css_class="col-sm-2"),
                Div('mst_auth', css_class="col-sm-2"),
                Div('mst_auth_date', css_class="col-sm-5"),
                css_class="row"
            ),
            Div(
                Div('finyear', css_class="col-sm-3"),
                Div('mislipdate', css_class="col-sm-3"),
                Div('matgrp', css_class="col-sm-3"),
                Div('mislipno', css_class="col-sm-3"),
                css_class="row"
            ),
            Div(
                Div('pono', css_class="col-sm-4"),
                Div('mprno', css_class="col-sm-5"),
                Div('recdby', css_class="col-sm-3"),

                css_class="row"
            ),
            Div(

                Div('suppname', css_class="col-sm-8"),
                Div('note', css_class="col-sm-2"),

                css_class="row"
            ),

        )

        self.helper['pono'].wrap(Field, ref="ref_pono")
        self.helper['suppname'].wrap(Field, ref="ref_suppname")

    def clean(self):
        cleaned_data=super(mislipeditForm,self).clean()
        print(cleaned_data)

        pono=self.cleaned_data.get("pono")
        matgrp = self.cleaned_data.get("matgrp")
        if matgrp  in (16, 19, 27):
            pass
        else:
            if verifyPO(pono)==False:
                self.add_error('pono',forms.ValidationError('PO not valid'))
        mstauth = self.cleaned_data['mst_auth']        
        if mstauth:
            sql = "SELECT FinYear, MatGrp, MiSlipNo, DetailId, StocKNo, Des,Unit,QtyRecd, QtyAccepted, DateAccepted,PersonAccepted , qtyIn FROM MISlipDet_Mst where mislipno=" + str(self.cleaned_data['mislipno']) + " and matgrp=" + str(self.cleaned_data['matgrp']) + " and finyear='" + self.cleaned_data['finyear'] + "' and qtyin is null"
            c1=runQuery('edssql', sql)['cursor']
            if len(c1)>0:
                self.add_error(field=None, error=forms.ValidationError("This Mi slip cannot be authorized ! One or more item is not stock charged!"))
        else:
            sql="select * from accmislip where  mislipno=" + str(self.cleaned_data['mislipno']) + " and matgroup=" + str(self.cleaned_data['matgrp']) + " and docyearid='" + self.cleaned_data['finyear'] + "'"
            print(sql)
            c1 = runQuery('accounts', sql)['cursor']
            if len(c1) > 0:
                self.add_error(field=None, error=forms.ValidationError("This Mi slip authorization cannot be revoked!"))

    def clean_mislipdate(self):
        #print('dtate')
        return datetime.datetime.strptime(str(self.cleaned_data['mislipdate']), "%Y-%m-%d").strftime("%d-%b-%Y")

    def clean_matgrp(self):
        matgrp=self.cleaned_data['matgrp']
        if verifyMatgrp(matgrp):
            return matgrp
        else:
            self.add_error('matgrp', forms.ValidationError('Mat Group not valid'))
        return matgrp
    def clean_st_auth(self):
        stauth = self.cleaned_data['st_auth']
        #check for bill
        if stauth:
            sql = "select * from mislipbills where mislipno=" + str(self.cleaned_data['mislipno']) + " and matgrp=" + str(self.cleaned_data['matgrp']) + " and finyear='" + self.cleaned_data['finyear'] + "'"
            c1 = runQuery('incomingstore', sql)['cursor']
            if len(c1) > 0:
                return self.cleaned_data['st_auth']
            else:
                self.add_error('st_auth', forms.ValidationError("No Bill Enttered !"))
        else:
            return stauth
        # check for items
        if stauth:
            sql = "select * from mislipdet where mislipno=" + str(self.cleaned_data['mislipno']) + " and matgrp=" + str(self.cleaned_data['matgrp']) + " and finyear='" + self.cleaned_data['finyear'] + "'"
            c1 = runQuery('incomingstore', sql)['cursor']
            if len(c1) > 0:
                return self.cleaned_data['st_auth']
            else:
                self.add_error('st_auth', forms.ValidationError("No item Enttered !"))
        else:
            return stauth
        return stauth

    def clean_mst_auth(self):
        mstauth = self.cleaned_data['mst_auth']
        print(self.cleaned_data)
        

        return mstauth


    def clean_mst_auth_date(self):
        mstauth=self.cleaned_data['mst_auth']
        print(self.cleaned_data['mst_auth_date'])
        if mstauth and self.cleaned_data['mst_auth_date']==None:
            self.add_error('mst_auth_date', forms.ValidationError("Pl select date!"))
            return None
        elif mstauth and not(self.cleaned_data['mst_auth_date']==None):
            return datetime.datetime.strptime(str(self.cleaned_data['mst_auth_date']), "%Y-%m-%d").strftime("%d-%b-%Y")
        return None

    def save_update(self,request):

            sql='update mislip set '+update_values_of_query(self,request)+' where finyear=%r and matgrp=%r and mislipno=%r'%(self.cleaned_data['finyear'],self.cleaned_data['matgrp'],self.cleaned_data['mislipno'])
            print(sql)

            return runQuery('incomingstore', sql)

    def save_create(self,request):
        fields = ','.join(self.fields)

        sql = 'insert into mislip (%s) values(%s)' % ( insert_values_of_query(self,request))
        print(sql)
        # print(self.cleaned_data)
        return runQuery('incomingstore', sql)

class mislipitemeditForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(mislipitemeditForm,self).__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.render_hidden_fields = True
    finyear = forms.CharField(max_length=50)
    finyear.widget.attrs['readonly'] = True
    matgrp=forms.IntegerField()
    matgrp.widget.attrs['readonly'] = True
    mislipno=forms.IntegerField()
    mislipno.widget.attrs['readonly'] = True
    stockno=forms.CharField(max_length=50)
    stockno.widget.attrs['ref']='ref_stockno'
    des = forms.CharField(widget=forms.Textarea(attrs={'rows':5}),max_length=1000)
    des.widget.attrs['ref'] = 'ref_des'
    qtyrecd=forms.FloatField()
    unit = forms.CharField(max_length=50)
    stdwt = forms.FloatField(required=False)
    scalewt = forms.FloatField(required=False)
    billedwt = forms.FloatField(required=False)
    class Meta:
        exclude=('stdwt',)



    def clean(self):
        cleaned_data=super(mislipitemeditForm,self).clean()

    def clean_stockno(self):
        stockno=self.cleaned_data['stockno']
        #return stockno
        print(stockno)
        if verifyStockNoAgainstStmaster(stockno,self.cleaned_data['matgrp']):
            if verifyStocknoAgainstPO(stockno,self.cleaned_data['finyear'],self.cleaned_data['matgrp'],self.cleaned_data['mislipno']):
                return stockno
            else:
                self.add_error('stockno', forms.ValidationError('Stock no not in PO'))
        else:
            self.add_error('stockno', forms.ValidationError('Stock no not in Stock Master'))
        return stockno

    def save_update(self, request):
        sql = 'update mislipdet set ' + update_values_of_query(self,request) + ' where finyear=%r and matgrp=%r and mislipno=%r  and stockno=%r' % (
        self.cleaned_data['finyear'], self.cleaned_data['matgrp'], self.cleaned_data['mislipno'],
        self.cleaned_data['stockno'])

        print(sql)

        return runQuery('incomingstore', sql)

    def save_create(self, request):
        fields = ','.join(self.fields)

        sql = 'insert into mislipdet (%s) values(%s)' % insert_values_of_query(self, request)
        print(sql)
        # print(self.cleaned_data)
        return runQuery('incomingstore', sql)

class mislipmrreditForm(forms.Form):

    finyear = forms.CharField(max_length=50)
    finyear.widget.attrs['readonly'] = True
    matgrp=forms.IntegerField()
    matgrp.widget.attrs['readonly'] = True
    mislipno=forms.IntegerField()
    mislipno.widget.attrs['readonly'] = True
    mrrno=forms.ChoiceField()
    #addedit = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self,*args,**kwargs):
        super(mislipmrreditForm,self).__init__(*args,**kwargs)
        self.fields['mrrno'].choices=mrrchoices(self.initial['finyear'])
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.render_hidden_fields = True

    def clean(self):
        cleaned_data=super(mislipmrreditForm,self).clean()


    def save_update(self, request):

mi_website/templates/mi_website/hello.html
<button  style='padding-to:20px' class='btn btn-primary btn-sm' @click='click1'> add</button>

mi_website/templates/mi_website/index.html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/static/mi_website/favicon.ico">
    <title>frontend</title>
  <link href="/static/mi_website/js/app.js" rel="preload" as="script"><link href="/static/mi_website/js/chunk-vendors.js" rel="preload" as="script"></head>
  <body>
    <noscript>
      <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  <script type="text/javascript" src="/static/mi_website/js/chunk-vendors.js"></script><script type="text/javascript" src="/static/mi_website/js/app.js"></script></body>
</html>

mi_website/templates/mi_website/index_d.html
{% extends "mi_website/base_index.html" %}
{% block content %}

{% endblock content %}

mi_website/templates/mi_website/mrrview.html
{% comment %}
{% extends "mi_website/base.html" %}
{% endcomment %}
{% block content %}

    <div id="app1">
        <div class="row" >
            <span class="col-md-9  text-center bg-secondary" >
                <h4>View Add Edit MRRs</h4>
            </span>
            <span class="col-md-1">
                <a class="nav-link" href="#"  >{% if request.username  %} {{ request.username }} {% else %} [['Log_in']] {% endif %}</a>
            </span>

        </div>

        <div class="row bg-inf" >
            <div class="input-group">
                <div class="col-md-3 offset-2">
                    <label for="txtfinyear">Fin Year:</label>
                    <input type="text" class="form-control" value="{{ finyear }}" id="txtfinyear" disabled>
                </div>
                <div class="col-md-3">
                    <label for="mrrdate">Select Mrr date:</label>
                    <vue-date-pick
                        id="mrrdate"
                        input_class="form-control"
                        v-model="dated"
                        :format="'MM-DD-YYYY'"

                    >

                    </vue-date-pick>
                </div>
                <!--<span class="input-group-btn" style="padding-top:30px"><button type="submit" class= "btn btn-info" @click="dateclicked">Submit</button></span>-->
            </div>

        </div>
        <div class="row bg-inf" >
            <div class="col-md-12">
            <ktable
                    ref="ktable"
                    :key="key_ktable"
                    :apiurl="apiurl"

                    :groupfields="false"
                    :use-detail-row="true"
                    @rowclicked="rowclicked"
                    rowcolor=""
                    :sortable="false"
                    :use-action-button="true"
                    @forminputchange="handlemrrforminputchange"
                    :useprintbutton="true"
                    >
                    <template v-slot:addtext>new</template>
                 <template v-slot:detailrow="slotprops">


                <!-- Tab panes -->

                       <component :is="c[slotprops.index]"
                                  :key="key_c"
                                  :ref="'c_'+slotprops.index"
                                                 :apiurl="urlmrrvalues"
                                                 :groupfields="false"
                                                 :use-detail-row="false"
                                                    :use-action-button="!slotprops.item.inspauth"
                                                :sortable="false"

                                  rowcolor="lightgreen"

                                      >
                           <template  v-slot:printaction="{item}">
                        <p v-show="false">kk</p>
                    </template>
                       </component>



                         </template>
                    </ktable>
        </div>
    </div>
    </div>

{% endblock content %}

{% block cmp %}

    {% include "components/ktable-cmp.html" %}

{% endblock cmp %}

{% block jscript %}
<script>
var app=new Vue({
            el: '#app1',
            delimiters: ['[[', ']]'],
            data:{key:[],dated:"",apiurl:'',key_index_ktable:1,key_index_c:1,key_index_c1:1,key_index_c2:1,c:[],c1:[],c2:[],urlmislipitems:'',urlmrrs:'',urlmislipbills:'',urlmrrvalues:'',currentindex:'',},
            watch:{
                dated:function(){this.dateclicked();},
            },
            computed:{
                key_ktable:{
                    get:function(){return 'ktable'+this.key_index_ktable},
                    //set:function(newvalue){this.key_index_ktable=newvalue},
                },
                key_c:{
                    get:function(){return 'c'+this.key_index_c1},
                    //set:function(newvalue){this.key_index_c1=newvalue},
                },
                key_c1:{
                    get:function(){return 'c1'+this.key_index_c},
                   // set:function(newvalue){this.key_index_c=newvalue},
                },
                key_c2:{
                    get:function(){return 'c2'+this.key_index_c2},
                    //set:function(newvalue){this.key_index_c2=newvalue},
                },


            },

            methods:{
                datachanged:function(i){
                    //console.log('aqwerty');
                    this.$refs['c2_'+i].refreshData()
                },
                handlemrrforminputchange:function(e){
                    //console.log(e.target.name);
                    if(e.target.name=='pono') {
                        url="{% url 'getsuppaddfrompono' %}"+'?pono='+e.target.value;
                        axios.get(url)
                            .then((response) => {
                                //console.log(response);
                                this.$refs.ktable.$refs.mm1.$refs.ref_suppname.value = response.data.suppadd;



                                },function (error) {console.log(error);}
                        );
                        //this.$refs.ktable.$refs.mm1.$refs.ref_suppname.value = e.target.value;
                    };

                },
                handleforminputchangeinmislipitems:function(e,index){
                    //console.log(e.target.name);
                    if(e.target.name=='stockno') {
                        url="{% url 'getstocknodes' %}"+'?stockno='+e.target.value;
                        axios.get(url)
                            .then((response) => {
                                //console.log(response);

                                this.$refs['c_'+index].$refs.mm1.$refs.ref_des.value = response.data.stockdes;



                                },function (error) {console.log(error);}
                        );
                    };

                },
                handleforminputchangeinmislipibills:function(e,index){
                    console.log(e.target.name);
                },
                dateclicked:function(){
                    //console.log('date clicked');
                    //this.key_index_ktable=1;
                    this.key_index_c=1;
                    this.key_index_c1=1;
                    this.key_index_c2=1;
                    this.apiurl="{%  url 'ajax_mrrs'  %}?finyear={{ finyear }}&dated="+this.dated;
                    this.key_index_ktable+=1;
                },
                rowclicked:function(item,index){
                    //console.log(item);
                    this.urlmrrvalues='';
                    this.c[this.currentindex]='';
                    this.key_c+=1;
                    this.currentindex=index;
                     this.urlmrrvalues="{%  url 'mrrvalues'  %}"+"?finyear="+item.finyear+"&mrrno="+item.mrrno;
                    //console.log(this.urlmislipitems);
                    this.c[index]=ktable;
                    this.key_c+=1;






                    //this.keyktable+=1;
                    this.key_index_c+=1;
                    this.key_index_c1+=1;
                    this.key_index_c2+=1;
                },

            },

})

$(function(){
  $("#__form").on("change", "#id_pono", function (event) {

      var pono = $(this).val();

  alert(pono);
  $.ajax({
      url: 'ajax/getsuppaddfrompono/',
      data: {'pono':pono},

      type: 'GET',
      dataType: 'json',
      success: function (data) {
          //alert(data.suppadd);
          $(".mislipeditform textarea[name='suppname']").val(data.suppadd);
      },
      error:function (data) {
          //alert(data.suppadd);
          $(".mislipeditform textarea[name='suppname']").val('');
      }
  })})});
</script>
{% endblock jscript %}